language: node_js
node_js:
  - "5.4"
  - "5.6"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g gulp
script:
  - gulp test
  - gulp build
  - gulp
notifications:
  slack: fnndsc:UohaXDsjFDVqZj5IfdC88XRa
